### ISSUE TITLE
Add a comment field for each table

### ISSUE THREAD

**Issue by mwvaughn** [TACC/paas#11]
I propose adding an optional short (say 255 char) comment field for each table. This would make PgREST table specs a little more self-documenting. This would make it easy to generate human-usable forms and renderings around PgREST.

**Comment by mwvaughn** [comment]
```json
{
  "table_name": "UserProfile",
  "root_url": "user-profile",
  "comment": "optional descriptive comment for the table"
}
```

**Comment by NotChristianGarcia** [comment]
Added in #15.
