### ISSUE TITLE
Support for table-level constraints

### ISSUE THREAD

**Issue by mwvaughn** [TACC/paas#12]
I am requesting support for table-level constraints. Specifically, and to start with, we need multi-column unique constraints for the A2CPS project. I propose the following extension to the PgREST table definition:

```json
{
	"table_name": "UserProfile",
	"root_url": "user-profile",
	"constraints": {
		"unique": {
			"first_last": ["first_name", "last_name"]
		}
	},
	"columns": {
		"user_profile_id": {
			"data_type": "serial",
			"primary_key": true
		},
		"username": {
			"unique": true,
			"data_type": "varchar",
			"char_len": 255
		},
		"first_name": {
			"null": true,
			"data_type": "varchar",
			"char_len": 255
		},
		"last_name": {
			"null": true,
			"data_type": "varchar",
			"char_len": 255
		}
	}
}
```

In this trivial example, all User Profile records would be forced have a unique combination of first and last name. On the backend, this would map roughly to:

```sql
CREATE UNIQUE INDEX UserProfile_first_last ON UserProfile(first_name, last_name)
```

**Comment by mwvaughn** [comment]
We can talk through other constraint designs later - I just wanted to put forward a proposal for unique constraints.

**Comment by NotChristianGarcia** [comment]
Added in #15.
