### ISSUE TITLE
Improvement: Don't enforce "limit" by default on queries

### ISSUE THREAD

**Issue by mwvaughn** [TACC/paas#36]
If I am doing a query on a table, I expect to get all the rows back if I do not specify a limit. This is equivalent to `FROM table SELECT * WHERE %CRITERA;` In the current pgrest implementation, I get the first 10 records back, which was a bit surprising. So, I either have to arbitrarily provide a large value for `'limit` or iterate through the responses, which adds at minimum, one additional API call just to do a select-type operation.

**Comment by NotChristianGarcia** [comment]
- Table level limit. Default which a user can change based on table usage.
- limit=0 as unlimited limit.
