### ISSUE TITLE
Materialized View support alongside regular views.

### ISSUE THREAD

**Issue by NotChristianGarcia** [TACC/paas#55]
Pat Scherer referenced wanting materialized view support in PgREST for some future work.

**Comment by NotChristianGarcia** [comment]
This can be either a complete replication of views, but with different function names. Or this can be an additional field in views that can then determine whether or not to use materialized views during run time. As in "view.mine", or if materialized = True, "materialized_view.mine".

**Comment by pscherer-tacc** [comment]
Not sure it matters from a caller's perspective whether you separate material views from views or treat as a parameter. Some fundamental differences between materialized views and views that you will need to support may dictate the optimum approach:
- Views use simpler queries constrained to a single table; materialized views support more complex queries which include joins of multiple tables
- View queries can be edited (with some notable constraints) using "CREATE or UPDATE query"; materialized views must be dropped and recreated (cannot be directly edited). 
- Unlike views which provide a dynamic view of current data; materialized views can be used to persist (freeze) the data within the view until the view is manually refreshed. The api method needs to support the REFRESH request. If materialized views are used heavily, the REFREH MATERIALIZED VIEW CONCURRENTLY request will also need to be supported.  

Based on the reports that are currently provided as well as new requests for reporting in A2CPS, I anticipate materialized views to be more heavily used than normal views. Use cases include data curation and aggregating data across multiple instrument tables (such as biosample collection ("bscp") and the EHR assays for those biosamples).
