### ISSUE TITLE
Clarify whether UPDATETIME and CREATETIME are case sensitive

### ISSUE THREAD

**Issue by mwvaughn** [TACC/paas#7]
It isn't clear from the docs whether `UPDATETIME` and `CREATETIME` are case sensitive. If they are, it should be stated, but I would suggest instead making them case-insensitive and defaulting to the lower case form in the docs.

**Comment by NotChristianGarcia** [comment]
Case insensitive! Updated in docs.
https://tapis.readthedocs.io/en/latest/technical/pgrest.html
