### ISSUE TITLE
Clarify whether 'on_update' is supported for foreign key constraints

### ISSUE THREAD

**Issue by mwvaughn** [TACC/paas#9]
PostgreSQL lets us define behavior for deletes but also updates. Can we clarify whether `on_update` is supported in PgREST?

**Comment by NotChristianGarcia** [comment]
Added support for `on update` alongside `on_delete`, this actually required a change in the foreign key table definition. There is now an `on_event` method that takes `on delete` or `on update` (case insensitive) along with `event_action` that takes which action to do after the specified `on_event` event.
Updated in docs.
https://tapis.readthedocs.io/en/latest/technical/pgrest.html
